# Generated by Django 4.0.1 on 2022-01-25 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(db_column='podloze', max_length=512, unique=True, verbose_name='podłoże')),
            ],
            options={
                'db_table': 'podloze',
            },
        ),
        migrations.CreateModel(
            name='Bullet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nazwa', max_length=1024, unique=True, verbose_name='nazwa')),
            ],
            options={
                'db_table': 'Pocisk',
            },
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='czynnik', max_length=64, verbose_name='czynnik')),
                ('parameter', models.CharField(db_column='parametr', max_length=64, verbose_name='parametr')),
                ('temperature', models.SmallIntegerField(db_column='temperatura', verbose_name='temperatura')),
                ('filling', models.FloatField(db_column='wypelnienie', verbose_name='wypełnienie')),
            ],
            options={
                'db_table': 'Czynniki',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(blank=True, db_column='material', max_length=1024, verbose_name='materiał')),
                ('factor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.factor')),
            ],
        ),
        migrations.CreateModel(
            name='Ricochet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.material')),
            ],
            options={
                'db_table': 'rykoszet',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='nazwa', max_length=1024, unique=True, verbose_name='nazwa')),
            ],
            options={
                'db_table': 'Bron',
            },
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('sample_id', models.CharField(db_column='id_proby', max_length=64, primary_key=True, serialize=False, verbose_name='id próby')),
                ('temperature', models.FloatField(blank=True, db_column='temperatura', null=True)),
                ('atmosferic_conditions', models.TextField(db_column='warunki_atmosferyczne', verbose_name='warunki_atmosferyczne')),
                ('wind_speed', models.IntegerField(db_column='predkosc_wiatru', verbose_name='predkosc_wiatru')),
                ('link', models.CharField(max_length=80)),
                ('link_caliber', models.CharField(db_column='link_kaliber', default='1', max_length=80, verbose_name='link kaliber')),
                ('camera', models.CharField(db_column='kamera_zwykla', default='1', max_length=64, verbose_name='kamera zwykła')),
                ('slowmotion_camera', models.CharField(db_column='kamera_szybka', default='1', max_length=64, verbose_name='kamera szybka')),
                ('ir_camera', models.CharField(db_column='kamera_ir', default='1', max_length=64, verbose_name='kamera ir')),
                ('photo', models.ImageField(db_column='zdjecie', null=True, upload_to='images/', verbose_name='zdjęcie')),
                ('base', models.ForeignKey(db_column='podloze', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.base')),
                ('bullet', models.ForeignKey(db_column='id_pocisku', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.bullet')),
                ('factor', models.ForeignKey(db_column='czynnik', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.factor')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.material')),
                ('ricochet', models.ForeignKey(db_column='rykoszet', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.ricochet')),
                ('weapon', models.ForeignKey(db_column='id_broni', on_delete=django.db.models.deletion.DO_NOTHING, to='proba_strzelnicza.weapon')),
            ],
            options={
                'db_table': 'Proba_Strzelnicza',
            },
        ),
    ]
